stages:
  - build
  - clean
  - upload
  - cache
  
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION

build:
  stage: build
  tags: [ "docker" ]
  image: blang/latex:ctanfull
  script:
    - pdflatex main.tex
    - mv main.pdf resume.pdf
  artifacts:
    paths:
      - "resume.pdf"
    expire_in: '1 week'

clean:
  stage: clean
  tags: [ "shell" ]
  script: 
    - qpdf resume.pdf Zachary-Rohrbach-Resume.pdf
    - exiftool -all:all= Zachary-Rohrbach-Resume.pdf
  artifacts:
    paths:
      - "Zachary-Rohrbach-Resume.pdf"

upload:
  stage: upload
  tags: [ "docker" ]
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp "Zachary-Rohrbach-Resume.pdf" s3://$S3_BUCKET_NAME
  only:
    - main

cache:
  stage: cache
  tags: [ "shell" ]
  script:
    - curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "X-Auth-Email: $CF_EMAIL" -H "Authorization: Bearer $CF_AUTH" -H "Content-Type: application/json" --data '{"purge_everything":true}' | jq
  only:
    - main
