stages:
  - build
  - clean
  - upload
  - cloudflare
  
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION

build-cv:
  stage: build
  tags: [ "docker" ]
  image: blang/latex:ctanfull
  script:
    - pdflatex cv.tex
  artifacts:
    paths:
      - "cv.pdf"
    expire_in: '1 week'

build-resume:
  stage: build
  tags: [ "docker" ]
  image: blang/latex:ctanfull
  script:
    - pdflatex resume.tex
  artifacts:
    paths:
      - "resume.pdf"
    expire_in: '1 week'

clean-cv:
  stage: clean
  tags: [ "docker" ]
  image: ubuntu:latest
  before_script:
    - apt update
    - apt install qpdf exiftool -y
  script: 
    - qpdf cv.pdf Zachary-Rohrbach-CV.pdf
    - exiftool -all:all= Zachary-Rohrbach-CV.pdf
  artifacts:
    paths:
      - "Zachary-Rohrbach-CV.pdf"

clean-resume:
  stage: clean
  image: ubuntu:latest
  before_script:
    - apt update
    - apt install qpdf exiftool -y
  script: 
    - qpdf resume.pdf Zachary-Rohrbach-Resume.pdf
    - exiftool -all:all= Zachary-Rohrbach-Resume.pdf
  artifacts:
    paths:
      - "Zachary-Rohrbach-Resume.pdf"

upload-pdfs:
  stage: upload
  tags: [ "docker" ]
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp "Zachary-Rohrbach-CV.pdf" s3://$S3_BUCKET_NAME
    - aws s3 cp "Zachary-Rohrbach-Resume.pdf" s3://$S3_BUCKET_NAME
  only:
    - main

cloudflare:
  stage: cloudflare
  image: ubuntu:latest
  before_script:
    - apt update
    - apt install curl -y
  script:
    - |
      curl \
        -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
        -H "X-Auth-Email: $CF_EMAIL" \
        -H "Authorization: Bearer $CF_AUTH" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'
  only:
    - main
