stages:
  - build
  - ls

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION
  BUCKET_NAME: $BUCKET_NAME

build:
  stage: build
  tags: [ "docker" ]
  image: blang/latex:ctanfull
  script:
    - pdflatex main.tex
    - mv main.pdf Zachary-Rohrbach-Resume.pdf
  artifacts:
    paths:
      - "Zachary-Rohrbach-Resume.pdf"
      expire_in: 1 week

ls:
  stage: ls
  tags: [ "docker" ]
  script:
    - pwd
    - ls -al

# upload:
#   tags: [ "docker" ]
#   image: amazon/aws-cli
#   script:
#     - aws s3 cp ./Zachary-Rohrbach-Resume.pdf s3://$BUCKET_NAME