name: Build & Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX Resume
        uses: xu-cheng/latex-action@2.5.0
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true
          extra_fonts: |
            ./fonts/*.ttf

      - name: Rename PDF
        run: |
          mv resume.pdf Zachary-Rohrbach-Resume.pdf
          
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: DigitalOcean
          region: 'US'
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Interact with object storage
        run: |
          s3cmd put "Zachary-Rohrbach-Resume.pdf" s3://${{ secrets.BUCKET_NAME }}

      - name: Cloudflare Cache
        run: |
          curl \
            -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "X-Auth-Email: ${{ secrets.CF_EMAIL }}" \
            -H "Authorization: Bearer ${{ secrets.CF_AUTH }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
