name: CI - PR Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-upload-delete:
    name: Build, Upload, & Delete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile LaTeX Resume
        uses: xu-cheng/latex-action@2.7.0
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true
          extra_fonts: |
            ./fonts/*.ttf

      - name: Rename PDF
        run: |
          cp resume.pdf ci-test.pdf
          mv resume.pdf Zachary-Rohrbach-Resume.pdf
          
      - name: Set Up S3cmd CLI
        uses: s3-actions/s3cmd@v1.3.0
        with:
          provider: digitalocean
          region: NYC3
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Upload PDF To Bucket
        run: |
          s3cmd put -P ci-test.pdf s3://${{ secrets.BUCKET_NAME }}
          
      - name: Delete PDF
        run: |
          s3cmd del s3://${{ secrets.BUCKET_NAME }}/ci-test.pdf
          
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: resume
          path: Zachary-Rohrbach-Resume.pdf
